Add hello world in php
devstrons/hello-world pull request #44
Opened 2021-09-04 06:19 UTC by irsayvid

2021-09-04 08:20 UTC, shuklaritvik06 approved these changes
LGTM! Thanks for the contribution!

2021-09-05 13:16 UTC, vsnthdev commented
Kindly, finish writing the full article with details like:

1. Why use PHP?
2. Where is PHP used?
3. Popular frameworks in PHP?
4. Links to well-written projects in PHP
5. How to get started and set up a dev environment to write PHP code, etc.

We do not accept code snippets without the articles.

2021-09-05 13:24 UTC, irsayvid commented
It wasn't mentioned in the contributing guidelines. No issues. Should I write in my preferred platform and link it here or can I link a blog which already has the required information?

2021-09-05 16:11 UTC, vsnthdev commented
As the project is currently in active development, the contributing guidelines aren't fully written yet, my apologies for that.
You should edit the markdown file you have submitted and write a genuine article of your own there. In other words, write the in the markdown file and update this PR.

2021-09-06 04:38 UTC, irsayvid commented
@vsnthdev review this and let me know if any further changes are needed

2021-09-06 17:35 UTC, Panquesito7 requested changes

2021-09-06 17:35 UTC, Panquesito7 commented on lang/php.md
> +Docs: PHP is a popular general-purpose scripting language that is especially suited to web development. It is a widely-used, free, and efficient alternative to competitors such as Microsoft's ASP. It
A lot of grammar and spelling issues.
```suggestion
Docs: PHP is a popular general-purpose scripting language that is especially suited to web development. It is a widely-used, free, and efficient alternative to competitors such as Microsoft's ASP. It is a powerful tool for making web pages dynamic and interactive. It is very efficient and can serve millions of hits per day. It is easy to integrate and supports many databases such as MySQL. It is easy to learn and uses both procedural and object-oriented programming. Using PHP, it is easy to modify the database and restrict access to different pages for different users. Laravel and Codeigniter are two popular frameworks in PHP. [Here](https://hackr.io/blog/php-projects) is a blog for users to get started with PHP, how to set up and write your first hello world in PHP. It contains few interesting projects you can do in PHP. 

```

2021-09-07 03:25 UTC, Panquesito7 commented
The [**contributing guidelines**](https://github.com/devstrons/hello-world#%EF%B8%8F-contribution-guidelines) were updated now. You can update your PR properly now. 🙂

2021-09-07 06:24 UTC, irsayvid commented
@vsnthdev @Panquesito7  please review the readme file, proofread the article and suggest if any changes are needed.

2021-09-07 10:14 UTC, vsnthdev requested changes
You've done an awesome job @irsayvid ⚡ keep it up!

2021-09-07 10:14 UTC, vsnthdev commented on lang/php.md
> +Navigate to https://www.apachefriends.org/download.html and download the latest stable version of PHP according to your OS (windows/Linux/OSX)
Change line 50 to 👇 

```
[Click here](https://www.apachefriends.org/download.html) to download the latest stable version of PHP according to your OS (windows/Linux/OSX)
```

2021-09-07 10:14 UTC, vsnthdev commented on lang/php.md
> +echo "Hello World!";
Indent this line with 4 spaces.

2021-09-07 10:14 UTC, vsnthdev commented on lang/php.md
> +echo "Hello World!";
Indent this line with 4 spaces.

2021-09-07 10:14 UTC, vsnthdev commented on lang/php.md
> +Navigate to  http://localhost/hello/hello.php in your preferred browser.
Change line 69 to 👇 

```
Navigate to [http://localhost/hello/hello.php](http://localhost/hello/hello.php) in your preferred browser.
```

2021-09-07 10:14 UTC, vsnthdev commented on lang/php.md
> +# PHP is case insensitive!
Remove this heading and this point anywhere after line 37 (while setting up the dev environment.

2021-09-07 11:19 UTC, irsayvid commented
I've updated. Please check it once again.

2021-09-07 13:00 UTC, merged

2021-09-07 13:10 UTC, vsnthdev commented
**Additional modifications to be done to this document:**

1. Add an SEO friendly title
2. Indent the first code block properly so it looks good

2021-09-07 20:18 UTC, Panquesito7 commented on lang/php.md
> +## Setting up PHP environment locally:
```suggestion
## Setting up PHP environment locally
```

2021-09-07 20:18 UTC, Panquesito7 commented on lang/php.md
> +echo "Hello World!";
I think this missed a 4-line indentation?