Update pull request template
devstrons/hello-world pull request #59
Opened 2021-09-11 00:12 UTC by Panquesito7

**Description**

- Update pull request template with more information and proper grammar.

This PR fixes #

**Notes for Reviewers:**

**[Signed commits](https://github.com/DevsTrons/hello-world/blob/master/CONTRIBUTING.md)**

- [x] Yes, I am a Member of **DEVSTRONS'**

**Discord id** (eg: DEVSTRONS'#0238):

- Panquesito7#3723

2021-09-11 13:28 UTC, amino19 requested changes

2021-09-11 13:28 UTC, amino19 commented on .github/pull_request_template.md
> +- Your Discord ID <!-- Enter your Discord ID -->
@Panquesito7: I already gave the example, no need for this extension of keywords.
```suggestion
<!-- Enter your Discord ID -->
```

2021-09-11 13:31 UTC, amino19 commented
@vsnthdev: Pl request further changes to Pull Request template as you said, you have an idea!
Let's work on it now! :rocket:

2021-09-11 14:48 UTC, vsnthdev commented
We can use GitHub Form Schema to improve things for the PR template. Read [more about this here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema). I'll be sending you a PR with the new issue template soon.

2021-09-12 16:48 UTC, Panquesito7 commented
> We can use GitHub Form Schema to improve things for the PR template. Read [more about this here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema). I'll be sending you a PR with the new issue template soon.

AFAIK, forms cannot be used in pull request templates.

2021-09-19 13:30 UTC, merged

2021-09-19 13:30 UTC, vsnthdev commented
Yup, that looks good to me 👍